set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if(NOT DEFINED LLVM_MINGW_ROOT)
    set(LLVM_MINGW_ROOT $ENV{LLVM_MINGW_ROOT})
endif()

set(TARGET_TRIPLE x86_64-w64-mingw32)

set(CMAKE_C_COMPILER ${LLVM_MINGW_ROOT}/bin/${TARGET_TRIPLE}-clang)
set(CMAKE_CXX_COMPILER ${LLVM_MINGW_ROOT}/bin/${TARGET_TRIPLE}-clang++)
set(CMAKE_RC_COMPILER ${LLVM_MINGW_ROOT}/bin/${TARGET_TRIPLE}-windres)
set(CMAKE_FIND_ROOT_PATH ${LLVM_MINGW_ROOT}/${TARGET_TRIPLE})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
